# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!

target 'MainProject' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod "AProject_Category", :path => "../AProject_Category/"
    pod "AProject", :path => "../AProject/"
    
    pod "MailProject_Category", :path => "../MailProject_Category/"
    pod "MailProject", :path => "../MailProject/"
end
